### ISSUE TITLE
missing protocol icon

### ISSUE THREAD

**Issue by hethhhhh** [EionRobb/purple-hangouts-attempt2#238]
Hey there! This is a very simple problem, hangouts protocol doesn't have an icon so it's hard to say if a contact is a hangouts contact or some other protocol. Thanks!

**Comment by EionRobb** [comment]
hi hi :)

There are protocol icons - https://github.com/EionRobb/purple-hangouts/commit/c5fcb92e5eac1768cfe5d09132e1eb4c337b2f33
If you're on Linux then your distro will probably be providing them, but if you're on Windows you'll need to pop them into the C:\Program Files (x86)\Pidgin\pixmaps\pidgin\protocols folders by hand

**Comment by hethhhhh** [comment]
superb, it's working now :)
